# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160321_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markup',
        ),
    ]
